### ISSUE TITLE
1.01 is requiring Minecraft 1.19.4

### ISSUE THREAD

**Issue by W2D3F1X2** [LynixPlayz/villager-schedules#1]
It's for 1.20, right

**Comment by BlueJayofEvil** [comment]
Same issue here.
1.02 is saying it needs 1.19.4, but it's supposed to be for 1.20.1

**Comment by Grenair** [comment]
same issue here

**Comment by alxstack** [comment]
Issue has been resolved. You will need to redownload the mod from modrinth.
